######################################################################
# Automatically generated by qmake (3.1) Mon Aug 28 16:37:03 2017
######################################################################

TEMPLATE = app 
TARGET = sudoku
INCLUDEPATH += .
QT += gui widgets

# Input
SOURCES += main.cc sudoku.cc sudokore.cc
HEADERS += sudoku.hh sudokore.hh
